"""add transaction_type table

Revision ID: 0608a8b318ec
Revises: 434a841ec9a8
Create Date: 2022-05-05 13:05:43.075159

"""
import sqlalchemy as sa
from alembic import op

from ftl_python_lib.models.sql.member import ModelMember
from ftl_python_lib.models.sql.transaction_type import ModelTransactionType

# revision identifiers, used by Alembic.
revision = "0608a8b318ec"
down_revision = "434a841ec9a8"
branch_labels = None
depends_on = None

create_trigger = """
    CREATE TRIGGER after___tablename___insert
    BEFORE INSERT
    ON __tablename__ FOR EACH ROW
    IF NEW.reference_id IS NULL THEN
        SET NEW.reference_id = NEW.id;
    END IF;
"""
drop_trigger = (
    f"DROP TRIGGER IF EXISTS after_{ModelTransactionType.__tablename__}_insert;"
)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        ModelTransactionType.__tablename__,
        sa.Column("id", sa.CHAR(length=36), nullable=False, autoincrement=False),
        sa.Column("reference_id", sa.CHAR(length=36), nullable=True),
        sa.Column("child_id", sa.CHAR(length=36), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("object_type", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("created_by", sa.CHAR(length=36), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_by", sa.CHAR(length=36), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_foreign_key(
        ModelTransactionType.__tablename__ + "_fk_created_by",
        ModelTransactionType.__tablename__,
        ModelMember.__tablename__,
        ["created_by"],
        ["id"],
    )

    op.execute(
        create_trigger.replace("__tablename__", ModelTransactionType.__tablename__)
    )

    op.bulk_insert(
        ModelTransactionType.__table__,
        [
            {
                "id": "c0297a2d-d0f4-49ec-89f5-7422bf465fdf",
                "name": "Payment Transactions",
                "object_type": "transaction",
                "created_by": "cb308772-c49d-11ec-9d64-0242ac120002",
            },
            {
                "id": "82e52b77-0197-400a-98b1-1b7af0e021b8",
                "name": "Securities Transactions",
                "object_type": "transaction",
                "created_by": "cb308772-c49d-11ec-9d64-0242ac120002",
            },
            {
                "id": "378de20a-8b03-415b-a398-fbc9534daff2",
                "name": "Trade Services Transactions",
                "object_type": "transaction",
                "created_by": "cb308772-c49d-11ec-9d64-0242ac120002",
            },
        ],
    )

    op.create_index("name", ModelTransactionType.__tablename__, ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(drop_trigger)
    op.drop_constraint(
        ModelTransactionType.__tablename__ + "_fk_created_by",
        ModelTransactionType.__tablename__,
        type_="foreignkey",
    )
    op.drop_index("name", table_name=ModelTransactionType.__tablename__)
    op.drop_table(ModelTransactionType.__tablename__)
    # ### end Alembic commands ###
