"""add provider subsubcategory table

Revision ID: 3d433c71c764
Revises: 3b2ccc0b6963
Create Date: 2022-05-27 12:54:06.598475

"""
import sqlalchemy as sa
from alembic import op

from ftl_python_lib.models.sql.member import ModelMember
from ftl_python_lib.models.sql.provider_subcategory import ModelProviderSubcategory

# revision identifiers, used by Alembic.
revision = "3d433c71c764"
down_revision = "3b2ccc0b6963"
branch_labels = None
depends_on = None


create_trigger = """
    CREATE TRIGGER after___tablename___insert
    BEFORE INSERT
    ON __tablename__ FOR EACH ROW
    IF NEW.reference_id IS NULL THEN
        SET NEW.reference_id = NEW.id;
    END IF;
"""
drop_trigger = (
    f"DROP TRIGGER IF EXISTS after_{ModelProviderSubcategory.__tablename__}_insert;"
)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        ModelProviderSubcategory.__tablename__,
        sa.Column("id", sa.CHAR(length=36), nullable=False, autoincrement=False),
        sa.Column("reference_id", sa.CHAR(length=36), nullable=True),
        sa.Column("child_id", sa.CHAR(length=36), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("description", sa.TEXT, nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("created_by", sa.CHAR(length=36), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_by", sa.CHAR(length=36), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_foreign_key(
        ModelProviderSubcategory.__tablename__ + "_fk_created_by",
        ModelProviderSubcategory.__tablename__,
        ModelMember.__tablename__,
        ["created_by"],
        ["id"],
    )

    op.execute(
        create_trigger.replace("__tablename__", ModelProviderSubcategory.__tablename__)
    )

    op.bulk_insert(
        ModelProviderSubcategory.__table__,
        [
            {
                "id": "2fc3580c-651d-4334-a638-a40e712ca9f6",
                "name": "API Gateway",
                "code": "apigw",
                "description": "API gateway is an application programming interface (API) management tool that sits between a client and a collection of backend services.",
                "created_by": "cb308772-c49d-11ec-9d64-0242ac120002",
            },
            {
                "id": "71320b40-8737-431d-b066-71a61b079b50",
                "name": "Content Delivery Network",
                "code": "cdn",
                "description": "Content Delivery Network (CDN), or Content Distribution Network, is a geographically distributed network of proxy servers and their data centers.",
                "created_by": "cb308772-c49d-11ec-9d64-0242ac120002",
            },
            {
                "id": "41190bc6-c0d0-4ca4-afbe-f50492df3e16",
                "name": "CI/CD Pipeline",
                "code": "cicd",
                "description": "CI/CD pipeline is a series of steps that must be performed in order to deliver a new version of software.",
                "created_by": "cb308772-c49d-11ec-9d64-0242ac120002",
            },
            {
                "id": "03d9189b-89e7-44d2-b170-e1156404d783",
                "name": "Code Repository",
                "code": "code",
                "description": "Code repository is a file archive and web hosting facility where programmers, developers, and designers store their software's source code.",
                "created_by": "cb308772-c49d-11ec-9d64-0242ac120002",
            },
            {
                "id": "573da0af-d096-4e3a-b113-038ee1f7631c",
                "name": "Container Registry",
                "code": "container",
                "description": "Container registry is a repository or a collection of repositories used to store and access container images.",
                "created_by": "cb308772-c49d-11ec-9d64-0242ac120002",
            },
            {
                "id": "97944992-cea5-4d19-91df-b9f4d31eaf68",
                "name": "Identity Management",
                "code": "identity",
                "description": "Framework of policies and technologies to ensure that the right users have the appropriate access to right technology resources.",
                "created_by": "cb308772-c49d-11ec-9d64-0242ac120002",
            },
            {
                "id": "07df029c-f2d3-4981-b28e-df00cc8b128f",
                "name": "Kubernetes Platform",
                "code": "k8s",
                "description": "Open-source container orchestration system for automating software deployment, scaling, and management.",
                "created_by": "cb308772-c49d-11ec-9d64-0242ac120002",
            },
            {
                "id": "99cfb19e-51b6-404f-86be-c51b7f288ea6",
                "name": "Load Balancing",
                "code": "lb",
                "description": "The process of distributing a set of tasks over a set of resources (computing units), with the aim of making their overall processing more efficient.",
                "created_by": "cb308772-c49d-11ec-9d64-0242ac120002",
            },
            {
                "id": "0f8b6316-030b-4e27-94fa-62ca3fda71f5",
                "name": "Service Mesh",
                "code": "mesh",
                "description": "Dedicated infrastructure layer for facilitating service-to-service communications between services or microservices, using a proxy.",
                "created_by": "cb308772-c49d-11ec-9d64-0242ac120002",
            },
            {
                "id": "d7f3912c-14b7-47df-aeaf-5b599521f7c3",
                "name": "Virtual Private Cloud",
                "code": "vpc",
                "description": "On-demand configurable pool of shared resources allocated within a public cloud environment, providing a certain level of isolation between the different organizations using cloud resources.",
                "created_by": "cb308772-c49d-11ec-9d64-0242ac120002",
            },
            {
                "id": "ba70d7fd-48c5-46db-9c43-40dfea3cfcae",
                "name": "Web Application Firewall",
                "code": "waf",
                "description": "Web Application Firewall (WAF) is a specific form of application firewall that filters, monitors, and blocks HTTP traffic to and from a web service.",
                "created_by": "cb308772-c49d-11ec-9d64-0242ac120002",
            },
            {
                "id": "71c8e74b-b8f2-4898-ae3f-8ea7f8525cd8",
                "name": "Cloud Cache",
                "code": "cache",
                "description": "Distributed cache is an extension of the traditional concept of cache used in a single locale, spanning multiple servers so that it can grow in size and in transactional capacity.",
                "created_by": "cb308772-c49d-11ec-9d64-0242ac120002",
            },
            {
                "id": "b11cd1e2-4cc7-4937-be7b-5992cd2e8a7d",
                "name": "Cloud RDBMS",
                "code": "rdbms",
                "description": "Relational database management system (RDBMS) is the software that matches and groups data by the same relational model (also known as schema).",
                "created_by": "cb308772-c49d-11ec-9d64-0242ac120002",
            },
            {
                "id": "b8ba59bc-6f17-4e0f-b4e9-4cb479b460d5",
                "name": "Cloud NoSQL",
                "code": "nosql",
                "description": "NoSQL database provides a mechanism for storage and retrieval of data that is modeled in means other than the tabular relations used in relational databases.",
                "created_by": "cb308772-c49d-11ec-9d64-0242ac120002",
            },
            {
                "id": "7b0314eb-fede-4d13-854d-18c30c3e0833",
                "name": "Cloud Secrets",
                "code": "secret",
                "description": "Secret sharing refers to methods for distributing a secret among a group of participants, each of whom is allocated a share of the secret.",
                "created_by": "cb308772-c49d-11ec-9d64-0242ac120002",
            },
            {
                "id": "d645746b-dd96-4a78-80a3-7137b732dd91",
                "name": "Cloud Storage",
                "code": "storage",
                "description": "Cloud storage is a model of computer data storage in which the digital data is stored in logical pools, accessible over the internet.",
                "created_by": "cb308772-c49d-11ec-9d64-0242ac120002",
            },
            {
                "id": "72cc3961-b95e-486b-b08d-eda40ecbf47a",
                "name": "Data Lake",
                "code": "lake",
                "description": "Data lake is a system or repository of data stored in its natural/raw format, including structured data (rows and columns), semi-structured data (logs, CSV, XML, JSON), unstructured data (emails, docs, PDFs) and binary data (images, audio, video).",
                "created_by": "cb308772-c49d-11ec-9d64-0242ac120002",
            },
            {
                "id": "a76cf375-ad6e-4b10-926f-85affe42bd5e",
                "name": "Data Warehouse",
                "code": "warehouse",
                "description": "Data Warehouse is a relational database that is designed and built for large data queries and analytics, business intelligence and decision making activities.",
                "created_by": "cb308772-c49d-11ec-9d64-0242ac120002",
            },
            {
                "id": "6f81cd83-e89b-4211-a29c-a02d32b2bd7d",
                "name": "FTP/SFTP",
                "code": "ftp",
                "description": "File Transfer Protocol (FTP) is a standard communication protocol used for the transfer of computer files from a server to a client on a computer network.",
                "created_by": "cb308772-c49d-11ec-9d64-0242ac120002",
            },
            {
                "id": "81b3d089-c8f1-4147-a3ff-a7eec60b58be",
                "name": "HTTP/HTTPS",
                "code": "http",
                "description": "Hypertext Transfer Protocol (HTTP) is an application layer protocol in the Internet Protocol suite model for distributed, collaborative, hypermedia information systems.",
                "created_by": "cb308772-c49d-11ec-9d64-0242ac120002",
            },
            {
                "id": "5d3bf644-12e7-41e6-ad78-85b8f2fb2005",
                "name": "Pub/Sub",
                "code": "pubsub",
                "description": "Publish/Subscribe (Pub/Sub) is an architectural design pattern that provides a framework for exchanging messages between senders (publishers) and receivers (subscribers).",
                "created_by": "cb308772-c49d-11ec-9d64-0242ac120002",
            },
            {
                "id": "b39e4c33-70e7-4421-92e1-2a23ef79db12",
                "name": "Queue",
                "code": "queue",
                "description": "Collection of entities that are maintained in a sequence and can be modified by the addition of entities at one end of the sequence and the removal of entities from the other end of the sequence.",
                "created_by": "cb308772-c49d-11ec-9d64-0242ac120002",
            },
            {
                "id": "9a18069d-4312-4527-a4e2-b4dd98c46f92",
                "name": "Streaming",
                "code": "streaming",
                "description": "Computer programming paradigm, equivalent to dataflow programming, event stream processing, and reactive programming, that allows some applications to more easily exploit a limited form of parallel processing.",
                "created_by": "cb308772-c49d-11ec-9d64-0242ac120002",
            },
        ],
    )

    op.create_index(
        "name", ModelProviderSubcategory.__tablename__, ["name"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(drop_trigger)
    op.drop_constraint(
        ModelProviderSubcategory.__tablename__ + "_fk_created_by",
        ModelProviderSubcategory.__tablename__,
        type_="foreignkey",
    )
    op.drop_index("name", table_name=ModelProviderSubcategory.__tablename__)
    op.drop_table(ModelProviderSubcategory.__tablename__)
    # ### end Alembic commands ###
