"""add account table

Revision ID: 434a841ec9a8
Revises: a6b2026c6047
Create Date: 2022-04-26 13:53:43.529789

"""
import uuid

import sqlalchemy as sa
from alembic import op

from ftl_python_lib.models.sql.account import ModelAccount
from ftl_python_lib.models.sql.member import ModelMember

# revision identifiers, used by Alembic.
revision = "434a841ec9a8"
down_revision = "a6b2026c6047"
branch_labels = None
depends_on = None

create_trigger = """
    CREATE TRIGGER after___tablename___insert
    BEFORE INSERT
    ON __tablename__ FOR EACH ROW
    IF NEW.reference_id IS NULL THEN
        SET NEW.reference_id = NEW.id;
    END IF;
"""
drop_trigger = f"DROP TRIGGER IF EXISTS after_{ModelAccount.__tablename__}_insert;"


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        ModelAccount.__tablename__,
        sa.Column("id", sa.CHAR(length=36), nullable=False),
        sa.Column("reference_id", sa.CHAR(length=36), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column("email", sa.CHAR(length=255), nullable=True),
        sa.Column("description", sa.TEXT, nullable=True),
        sa.Column("website", sa.CHAR(length=255), nullable=True),
        sa.Column("member", sa.TEXT, nullable=True),
        sa.Column("child_id", sa.CHAR(length=36), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("created_by", sa.CHAR(length=36), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_by", sa.CHAR(length=36), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_foreign_key(
        ModelAccount.__tablename__ + "_fk_created_by",
        ModelAccount.__tablename__,
        ModelMember.__tablename__,
        ["created_by"],
        ["id"],
    )

    op.execute(create_trigger.replace("__tablename__", ModelAccount.__tablename__))

    op.bulk_insert(
        ModelAccount.__table__,
        [
            {
                "id": str(uuid.uuid4()),
                "name": "Fintechless",
                "created_by": "cb308772-c49d-11ec-9d64-0242ac120002",
            }
        ],
    )

    op.create_index("name", ModelAccount.__tablename__, ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(drop_trigger)
    op.drop_constraint(
        ModelAccount.__tablename__ + "_fk_created_by",
        ModelAccount.__tablename__,
        type_="foreignkey",
    )
    op.drop_index("name", table_name=ModelAccount.__tablename__)
    op.drop_table(ModelAccount.__tablename__)
    # ### end Alembic commands ###
