"""add config table

Revision ID: 7109d8874bcf
Revises: 0bba47a3ab7d
Create Date: 2022-05-27 12:54:40.062063

"""
import uuid

import sqlalchemy as sa
from alembic import op

from ftl_python_lib.models.sql.config import ModelConfig
from ftl_python_lib.models.sql.member import ModelMember

# revision identifiers, used by Alembic.
revision = "7109d8874bcf"
down_revision = "0bba47a3ab7d"
branch_labels = None
depends_on = None

create_trigger = """
    CREATE TRIGGER after___tablename___insert
    BEFORE INSERT
    ON __tablename__ FOR EACH ROW
    IF NEW.reference_id IS NULL THEN
        SET NEW.reference_id = NEW.id;
    END IF;
"""
drop_trigger = f"DROP TRIGGER IF EXISTS after_{ModelConfig.__tablename__}_insert;"


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        ModelConfig.__tablename__,
        sa.Column("id", sa.CHAR(length=36), nullable=False, autoincrement=False),
        sa.Column("reference_id", sa.CHAR(length=36), nullable=True),
        sa.Column("child_id", sa.CHAR(length=36), nullable=True),
        sa.Column(
            "active", sa.BOOLEAN(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("activated_at", sa.DateTime(), nullable=True),
        sa.Column("var_key", sa.CHAR(length=255), nullable=False),
        sa.Column("var_value", sa.CHAR(length=255), nullable=True),
        sa.Column("ref_table", sa.CHAR(length=255), nullable=True),
        sa.Column("ref_key", sa.CHAR(length=36), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("created_by", sa.CHAR(length=36), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_by", sa.CHAR(length=36), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_foreign_key(
        ModelConfig.__tablename__ + "_fk_created_by",
        ModelConfig.__tablename__,
        ModelMember.__tablename__,
        ["created_by"],
        ["id"],
    )

    op.execute(create_trigger.replace("__tablename__", ModelConfig.__tablename__))

    op.bulk_insert(
        ModelConfig.__table__,
        [
            {
                "id": str(uuid.uuid4()),
                "var_key": "FTL_DOMAIN",
                "active": True,
                "created_by": "cb308772-c49d-11ec-9d64-0242ac120002",
            },
            {
                "id": str(uuid.uuid4()),
                "var_key": "FTL_SUBDOMAIN",
                "active": True,
                "created_by": "cb308772-c49d-11ec-9d64-0242ac120002",
            },
            {
                "id": str(uuid.uuid4()),
                "var_key": "FTL_CLOUD_PROVIDER",
                "active": True,
                "created_by": "cb308772-c49d-11ec-9d64-0242ac120002",
            },
            {
                "id": str(uuid.uuid4()),
                "var_key": "FTL_ACTIVE_REGION",
                "active": True,
                "created_by": "cb308772-c49d-11ec-9d64-0242ac120002",
            },
            {
                "id": str(uuid.uuid4()),
                "var_key": "FTL_PASSIVE_REGION",
                "active": True,
                "created_by": "cb308772-c49d-11ec-9d64-0242ac120002",
            },
            {
                "id": str(uuid.uuid4()),
                "var_key": "FTL_ACTIVE_VPC",
                "active": True,
                "created_by": "cb308772-c49d-11ec-9d64-0242ac120002",
            },
            {
                "id": str(uuid.uuid4()),
                "var_key": "FTL_PASSIVE_VPC",
                "active": True,
                "created_by": "cb308772-c49d-11ec-9d64-0242ac120002",
            },
            {
                "id": str(uuid.uuid4()),
                "var_key": "FTL_MSA_UUID_TTL",
                "active": True,
                "created_by": "cb308772-c49d-11ec-9d64-0242ac120002",
            },
            {
                "id": str(uuid.uuid4()),
                "var_key": "FTL_MSA_LATEST_LIMIT",
                "active": True,
                "created_by": "cb308772-c49d-11ec-9d64-0242ac120002",
            },
            {
                "id": str(uuid.uuid4()),
                "var_key": "FTL_DB_USERNAME",
                "active": True,
                "created_by": "cb308772-c49d-11ec-9d64-0242ac120002",
            },
            {
                "id": str(uuid.uuid4()),
                "var_key": "FTL_DB_PASSWORD",
                "active": True,
                "created_by": "cb308772-c49d-11ec-9d64-0242ac120002",
            },
            {
                "id": str(uuid.uuid4()),
                "var_key": "FTL_DB_ENGINE",
                "active": True,
                "created_by": "cb308772-c49d-11ec-9d64-0242ac120002",
            },
            {
                "id": str(uuid.uuid4()),
                "var_key": "FTL_DB_HOST",
                "active": True,
                "created_by": "cb308772-c49d-11ec-9d64-0242ac120002",
            },
            {
                "id": str(uuid.uuid4()),
                "var_key": "FTL_DB_PORT",
                "active": True,
                "created_by": "cb308772-c49d-11ec-9d64-0242ac120002",
            },
            {
                "id": str(uuid.uuid4()),
                "var_key": "FTL_DB_DATABASE",
                "active": True,
                "created_by": "cb308772-c49d-11ec-9d64-0242ac120002",
            },
            {
                "id": str(uuid.uuid4()),
                "var_key": "MESSAGE_DEFINITIONS_HOST",
                "active": True,
                "created_by": "cb308772-c49d-11ec-9d64-0242ac120002",
            },
            {
                "id": str(uuid.uuid4()),
                "var_key": "FTL_CLOUD_REGION_PRIMARY",
                "active": True,
                "created_by": "cb308772-c49d-11ec-9d64-0242ac120002",
            },
            {
                "id": str(uuid.uuid4()),
                "var_key": "FTL_RUNTIME_BUCKET",
                "active": True,
                "created_by": "cb308772-c49d-11ec-9d64-0242ac120002",
            },
            {
                "id": str(uuid.uuid4()),
                "var_key": "FTL_ENVIRONMENT",
                "active": True,
                "created_by": "cb308772-c49d-11ec-9d64-0242ac120002",
            },
        ],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(drop_trigger)
    op.drop_constraint(
        ModelConfig.__tablename__ + "_fk_created_by",
        ModelConfig.__tablename__,
        type_="foreignkey",
    )
    op.drop_table(ModelConfig.__tablename__)
    # ### end Alembic commands ###
