"""add member table

Revision ID: 8877fe352467
Revises: 1eddc1b95bd8
Create Date: 2022-04-26 13:40:24.736856

"""
import sqlalchemy as sa
from alembic import op

from ftl_python_lib.models.sql.member import ModelMember

# revision identifiers, used by Alembic.
revision = "8877fe352467"
down_revision = "1eddc1b95bd8"
branch_labels = None
depends_on = None

create_trigger = """
    CREATE TRIGGER after___tablename___insert
    BEFORE INSERT
    ON __tablename__ FOR EACH ROW
    IF NEW.reference_id IS NULL THEN
        SET NEW.reference_id = NEW.id;
    END IF;
"""
drop_trigger = f"DROP TRIGGER IF EXISTS after_{ModelMember.__tablename__}_insert;"


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        ModelMember.__tablename__,
        sa.Column("id", sa.CHAR(length=36), nullable=False),
        sa.Column("reference_id", sa.CHAR(length=36), nullable=True),
        sa.Column("child_id", sa.CHAR(length=36), nullable=True),
        sa.Column("auth_id", sa.CHAR(length=36), nullable=False),
        sa.Column("email", sa.CHAR(length=255), nullable=True),
        sa.Column("first_name", sa.CHAR(length=255), nullable=True),
        sa.Column("last_name", sa.CHAR(length=255), nullable=True),
        sa.Column("avatar", sa.TEXT, nullable=True),
        sa.Column("role", sa.CHAR(length=255), nullable=False),
        sa.Column(
            "invite", sa.BOOLEAN(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("created_by", sa.CHAR(length=36), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_by", sa.CHAR(length=36), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )

    op.execute(create_trigger.replace("__tablename__", ModelMember.__tablename__))

    op.bulk_insert(
        ModelMember.__table__,
        [
            {
                "id": "cb308772-c49d-11ec-9d64-0242ac120002",
                "auth_id": "cb308772-c49d-11ec-9d64-0242ac120002",
                "name": "Fintechless Admin",
                "role": "owner",
                "created_by": "cb308772-c49d-11ec-9d64-0242ac120002",
            }
        ],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(drop_trigger)
    op.drop_table(ModelMember.__tablename__)
    # ### end Alembic commands ###
