"""add message_target table

Revision ID: 9f53a732fc25
Revises: 88b9ed8ff07c
Create Date: 2022-05-18 11:08:45.413484

"""
import uuid

import sqlalchemy as sa
from alembic import op

from ftl_python_lib.models.sql.member import ModelMember
from ftl_python_lib.models.sql.message_target import ModelMessageTarget

# revision identifiers, used by Alembic.
revision = "9f53a732fc25"
down_revision = "88b9ed8ff07c"
branch_labels = None
depends_on = None


create_trigger = """
    CREATE TRIGGER after___tablename___insert
    BEFORE INSERT
    ON __tablename__ FOR EACH ROW
    IF NEW.reference_id IS NULL THEN
        SET NEW.reference_id = NEW.id;
    END IF;
"""
drop_trigger = (
    f"DROP TRIGGER IF EXISTS after_{ModelMessageTarget.__tablename__}_insert;"
)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        ModelMessageTarget.__tablename__,
        sa.Column("id", sa.CHAR(length=36), nullable=False, autoincrement=False),
        sa.Column("reference_id", sa.CHAR(length=36), nullable=True),
        sa.Column("child_id", sa.CHAR(length=36), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("type", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("created_by", sa.CHAR(length=36), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_by", sa.CHAR(length=36), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_foreign_key(
        ModelMessageTarget.__tablename__ + "_fk_created_by",
        ModelMessageTarget.__tablename__,
        ModelMember.__tablename__,
        ["created_by"],
        ["id"],
    )

    op.execute(
        create_trigger.replace("__tablename__", ModelMessageTarget.__tablename__)
    )

    op.bulk_insert(
        ModelMessageTarget.__table__,
        [
            {
                "id": str(uuid.uuid4()),
                "name": "message_id",
                "type": "string",
                "created_by": "cb308772-c49d-11ec-9d64-0242ac120002",
            },
            {
                "id": str(uuid.uuid4()),
                "name": "amount",
                "type": "number",
                "created_by": "cb308772-c49d-11ec-9d64-0242ac120002",
            },
            {
                "id": str(uuid.uuid4()),
                "name": "currency",
                "type": "string",
                "created_by": "cb308772-c49d-11ec-9d64-0242ac120002",
            },
            {
                "id": str(uuid.uuid4()),
                "name": "sender_id",
                "type": "number",
                "created_by": "cb308772-c49d-11ec-9d64-0242ac120002",
            },
            {
                "id": str(uuid.uuid4()),
                "name": "sender_routing",
                "type": "string",
                "created_by": "cb308772-c49d-11ec-9d64-0242ac120002",
            },
            {
                "id": str(uuid.uuid4()),
                "name": "sender_account",
                "type": "string",
                "created_by": "cb308772-c49d-11ec-9d64-0242ac120002",
            },
            {
                "id": str(uuid.uuid4()),
                "name": "receiver_id",
                "type": "number",
                "created_by": "cb308772-c49d-11ec-9d64-0242ac120002",
            },
            {
                "id": str(uuid.uuid4()),
                "name": "receiver_routing",
                "type": "string",
                "created_by": "cb308772-c49d-11ec-9d64-0242ac120002",
            },
            {
                "id": str(uuid.uuid4()),
                "name": "receiver_account",
                "type": "string",
                "created_by": "cb308772-c49d-11ec-9d64-0242ac120002",
            },
            {
                "id": str(uuid.uuid4()),
                "name": "transaction_datetime",
                "type": "datetime",
                "created_by": "cb308772-c49d-11ec-9d64-0242ac120002",
            },
        ],
    )

    op.create_index("name", ModelMessageTarget.__tablename__, ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(drop_trigger)
    op.drop_constraint(
        ModelMessageTarget.__tablename__ + "_fk_created_by",
        ModelMessageTarget.__tablename__,
        type_="foreignkey",
    )
    op.drop_index("name", table_name=ModelMessageTarget.__tablename__)
    op.drop_table(ModelMessageTarget.__tablename__)
    # ### end Alembic commands ###
